@startuml DiagramName
skinparam backgroundColor #2E2E2E
skinparam class {
    BackgroundColor #3C3C3C
    ArrowColor White
    BorderColor White
    FontColor White
    AttributeFontColor White
    StereotypeFontColor White
    BorderThickness 1.5
}
skinparam note {
    BackgroundColor #4B4B4B
    BorderColor White
    FontColor White
}
hide circle
hide empty members
hide empty methods

class APawn {
    TSubclassOf<AController> AIControllerClass;
    unit32 bInputEnabled:1;
    FVector ControlInputVector;
    --
    APlayerState* PlayerState;
    AController* Controller;
}

class ADefaultPawn {
    USphereComponent* CollisionComponent;
    UPawnMovementComponent* MovementComponent;
}

class ACharactor {
    USkeletalMeshComponent* Mesh;
    UCharactorMovementComponent* CharactorMovement;
    UCapsuleComponent* CapsuleComponent;
}

class ASpectatorPawn {
    USpectatorPawnMovement
}

APawn <|-- ADefaultPawn
APawn <|-- ACharactor
ADefaultPawn <|-- ASpectatorPawn
@enduml