@startuml DiagramName
skinparam backgroundColor #2E2E2E
skinparam class {
    BackgroundColor #3C3C3C
    ArrowColor White
    BorderColor White
    FontColor White
    AttributeFontColor White
    StereotypeFontColor White
    BorderThickness 1.5
}
hide circle
hide empty members
hide empty methods

class ULevel {
    +TArray<AActor> Actors;
    +ALevelScriptActor* LevelScriptActor;
    +TArray<UModelComponent*> ModelComponents;
    +AWOrldSettings* WorldSettings; （Actors[0]）
}

class AActor extends ULevel {
    +TSet<UActorComponent*> OwnedComponents;
    +USceneComponent* RootComponent;
    +void Tick(float DeltaSeconds);
    +TArray<AActor*> Children;
    +TSet<UActorComponent*> ReplicatedComponents;
    +TArray<UActorComponent*> InstanceComponents;
    +UInputComponent* InputComponent;
    +AActor* Owner; （weak）
}
class AInfo extends AActor {
    +UBillboardComponent* SpriteComponent;
}

class ALevelScriptActor extends AActor {
    +unit32 bInputEnabled:1;
} 

class AWorldSettings extends ULevel {
    +TSubclassOf<class AGameMode> DefaultGameMode;
    +Other Settings
}


AWorldSettings --> AInfo
ALevelScriptActor --> ULevel
@enduml