@startuml DiagramName
skinparam backgroundColor #2E2E2E
skinparam class {
    BackgroundColor #3C3C3C
    ArrowColor White
    BorderColor White
    FontColor White
    AttributeFontColor White
    StereotypeFontColor White
    BorderThickness 1.5
}
skinparam note {
    BackgroundColor #4B4B4B
    BorderColor White
    FontColor White
}
hide circle
hide empty members
hide empty methods

class AActor {
    TSet<UActorComponent*> OwnedComponents;
    USenceComponent* RootComponent;
    void Tick(float DeltaSeconds);
    --
    TArray<AActor*> Children;
    AActor* Owner; (weak)
    TSet<UActorComponent*> ReplicatedComponents;
    TArray<UActorComponent*> InstanceComponents;

    UInputComponent* InputComponent;
} 

class APawn {
    TSubclassOf<AController> AIControllerClass;
    uint32 bInputEnabled:1;
    FVector ControlInputVector;
    --
    APlayerState* PlayerState;
    AController* Controller;
}

AActor <-- APawn
@enduml